apiVersion: v1
kind: Service
metadata:
  name: kafka-controller-1
spec:
  type: NodePort
  ports:
  - port: 7071
    targetPort: 7071
    name: metrics
  - port: 9092
    targetPort: 9092
    name: controller
  # - port: 9093
  #   targetPort: 9093
  #   name: controller
  selector:
    app: kafka-controller-1
