apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    name: metrics
  - port: 9092
    targetPort: 9092
    name: controller
  # - port: 9093
  #   targetPort: 9093
  #   name: controller
  selector:
    app: kafka-broker-1
