apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: local.registry.com:32555/prometheus:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
      imagePullSecrets:
      - name: privateregistry

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: kafka
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
