# Use the official Prometheus image as a base
FROM prom/prometheus

# Copy the Prometheus configuration file into the image
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Expose port 9090
# EXPOSE 9090
